baseURL = 'https://davido.io/'
languageCode = 'en-us'
title = 'davido.io'
theme = 'brutallydark'
pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown

[params]
  [params.author]
    email = 'david@davido.io'
    name = 'David Ontiveros'

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 3
  [[menu.footer]]
    name = "Github"
    url = "https://github.com/dcontiveros"
    weight = 1
  [[menu.footer]]
    name = "Gitlab"
    url = "https://gitlab.com/dcontiveros"
    weight = 2
  [[menu.footer]]
    name = "Instagram"
    url = "https://instagram.com/dcontiveros_irl"
    weight = 3
  [[menu.footer]]
    name = "Mastodon"
    url = "https://hachyderm.io/@dcontiveros"
    weight = 4
  [[menu.footer]]
    name = "Twitter"
    weight = 5
    url = "https://twitter.com/dcontiveros"
